extends Node
## AgentEmpire's sound.
##
## Buses: Master, Music, SFX, UI and Ambience (res://default_bus_layout.tres), their volumes
## from the Settings keys audio/master, audio/music, audio/sfx, audio/ui and audio/ambience
## (linear 0..1, 0 mutes), applied live. With audio/mute_unfocused the game fades out while its
## window is in the background.
##
## Cues: play(cue) and play_at(cue, position) name a cue from res://audio/cue_table.gd (its
## loudness, cooldown, voice limit, priority, music ducking) whose files are listed in
## res://audio/cue_files.gd (generated by scripts/fetch-audio.mjs). Each play picks a file at
## random (never the same one twice running) with a little pitch and volume variation. Players
## come from two pools: flat ones for the HUD and the town's news, and 3D ones placed in the
## world (under the WorldView, heard through a listener that follows the RTS camera). Bells and
## alerts dip the music while they ring.
##
## Ambience: a day bed (birdsong, a meadow wind) and a night bed (crickets), crossfaded with the
## SkyEnvironment's night amount. Music: a calm playlist with long silences between tracks,
## streamed. Both start with a town and fade with it.
##
## Hooks (all here, so other code only calls play/play_at for its own moments):
## - Realm: approvals answered, tasks sent, delivered, started, failed or sent back, incidents
##   (alarm bell, Font dark, rift, smoke, a spent Mana Seal's hand bell), Mana thresholds
##   (lanterns at 25%, the warning bell at 10%, the Dawn Bell on refill), research and new ages,
##   agents ranking up, parties formed. TownLink already rings the hand bell for approvals and
##   plays task_done and reward; HUD plays summon and reward; Game plays build_complete,
##   train_complete and need_houses.
## - Every BaseButton (and PopupMenu and TabBar) as it enters the tree: ui_click when pressed,
##   a faint ui_hover; every WindowFrame: ui_open and ui_close. A cue marked "click" in the
##   table (ui_confirm, a command, trade...) played in the same frame as the press stands in for
##   the click. Give a control the meta "audio_silent" to keep it quiet.
##
## Web: browsers keep audio suspended until the player clicks or presses a key; Godot resumes
## it on that first input. Until then nothing plays (sounds started while suspended would all
## burst out at once) and music and ambience wait. unlock() marks the moment too (the
## onboarding arrival card calls it). Headless runs use Godot's dummy driver: everything runs,
## silently.

## A cue started (tests and tools listen).
signal cue_played(cue: String)

const CueTable = preload("res://audio/cue_table.gd")
const CueFiles = preload("res://audio/cue_files.gd")

## Settings key -> bus name.
const VOLUME_KEYS := {
	"audio/master": "Master", "audio/music": "Music", "audio/sfx": "SFX", "audio/ui": "UI",
	"audio/ambience": "Ambience",
}
const MUTE_DB := -80.0
const POOL_FLAT := 20
const POOL_WORLD := 20
## The music's level over its files (normalised to -18 LUFS), the silence before the first
## track and between tracks (seconds, random in the range), and its fades.
const MUSIC_DB := -3.0
const MUSIC_FIRST_DELAY := Vector2(5.0, 10.0)
const MUSIC_GAP := Vector2(45.0, 110.0)
const MUSIC_FADE_IN := 2.0
const MUSIC_FADE_OUT := 1.5
## The ambience beds' level over their files (-24 LUFS) and how fast they fade in and out.
const AMBIENCE_DB := -2.0
const AMBIENCE_FADE := 3.0
## World sounds: the listener sits on the camera's ray this share of the way from the ground
## point at the centre of the view up to the camera, so zooming out softens the town a little;
## UNIT_SIZE is the distance (tiles) at which a world sound plays at its table loudness.
const LISTENER_LIFT := 0.35
const UNIT_SIZE := 12.0
const PANNING := 0.65
## Godot plays a world sound 3 dB under a flat one at UNIT_SIZE (constant-power panning), and at
## the default zoom the ear is about 10.5 tiles from the view's centre (-1.85 dB measured): this
## brings a world sound there back to its table loudness.
const WORLD_DB := 2.0
## How far the game fades out while unfocused, and how fast.
const UNFOCUSED_DB := -60.0
const FOCUS_FADE := 0.35
## Music ducking: attack and release time constants (seconds).
const DUCK_ATTACK := 0.08
const DUCK_RELEASE := 0.9
const RANKS := ["F", "E", "D", "C", "B", "A", "S"]
const MANA_LEVELS := ["normal", "dim", "warning", "depleted"]
## Incident kind -> cue. hand_bell incidents ring only for a spent Mana Seal (an approval's bell
## is TownLink's); dim_lanterns and the Mana pool's font_dark follow the Mana level instead.
const INCIDENT_CUES := {"alarm_bell": "alarm_bell", "font_dark": "font_dark", "rift": "rift", "smoke": "smoke"}

## One voice of a pool: the player and what it is playing.
class Voice:
	var player: Node
	var world: bool = false
	var cue: String = ""
	var priority: int = 0
	var started: float = 0.0
	var ends: float = 0.0
	var duck: float = 0.0
	var position: Vector3 = Vector3.ZERO

## Master switch: false plays nothing (cues still count as unknown or not).
var enabled: bool = true
## False on the web until the first click, key or touch (or unlock()).
var unlocked: bool = true
## False with the dummy driver (headless runs): cues are tracked as usual (cooldowns, voices,
## cue_played) but nothing reaches the AudioServer, so a run that quits mid-sound leaks no
## playbacks. Tools that record the mix set it back to true.
var playback: bool = true
## Tests: treat the running town as the Town Hall's, so the Realm hooks ring.
var assume_town: bool = false

var _rng := RandomNumberGenerator.new()
var _flat: Array[Voice] = []
var _world: Array[Voice] = []
var _world_root: WeakRef = null
var _world_node: Node3D = null
var _listener: AudioListener3D = null
var _sky: WeakRef = null
var _streams: Dictionary = {}
var _preload_queue: Array[String] = []
var _next_allowed: Dictionary = {}
var _last_file: Dictionary = {}
var _forced_variant: int = -1
var _warned: Dictionary = {}

var _duck_db: float = 0.0
var _focused: bool = true
var _focus_gain: float = 1.0
var _applied: Dictionary = {}

var _amb_day: AudioStreamPlayer
var _amb_night: AudioStreamPlayer
var _amb_level: float = 0.0
var _night: float = 0.0
var _night_poll: float = 0.0

var _music: AudioStreamPlayer
var _music_order: Array[int] = []
var _music_next_at: float = -1.0
var _music_ends: float = 0.0
var _music_gain: float = 0.0
var _music_fading_out: bool = false

## A press waiting for the end of the frame to click, whether a cue stood in for it, and the
## frame the last such cue played in (a handler connected before ours plays it first).
var _click_pending: bool = false
var _click_superseded: bool = false
var _stand_in_frame: int = -1

var _realm: Node = null
var _game: Node = null
var _settings: Node = null
## Realm baselines, so a reconnect (a fresh full state) never rings anything.
var _ranks: Dictionary = {}
var _parties: Dictionary = {}
var _mana_level: String = ""
var _mana_period: String = ""
var _age: int = 0
var _researching: bool = false


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_rng.randomize()
	unlocked = not OS.has_feature("web")
	playback = AudioServer.get_driver_name() != "Dummy"
	set_process_input(not unlocked)
	for i in POOL_FLAT:
		var p := AudioStreamPlayer.new()
		p.name = "Voice%d" % i
		add_child(p)
		var v := Voice.new()
		v.player = p
		_flat.append(v)
	_amb_day = _bed_player("AmbienceDay")
	_amb_night = _bed_player("AmbienceNight")
	_music = _bed_player("Music")
	_music.bus = &"Music"
	_music.finished.connect(_on_music_finished)
	var settings := get_node_or_null("/root/Settings")
	if settings != null:
		settings.changed.connect(_on_setting_changed)
	_apply_volumes()
	get_tree().node_added.connect(_on_node_added)
	for cue: String in CueFiles.FILES:
		for entry: Array in CueFiles.FILES[cue]:
			_preload_queue.append(String(entry[0]))
	_connect_town.call_deferred()


func _bed_player(node_name: String) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.name = node_name
	p.bus = &"Ambience"
	p.volume_db = MUTE_DB
	# Long files stream from the decoder; on the web the default "sample" playback would decode
	# a whole track into browser memory first.
	p.playback_type = AudioServer.PLAYBACK_TYPE_STREAM
	add_child(p)
	return p


## Realm, Game and Net come after this autoload: connect once they all exist.
func _connect_town() -> void:
	_realm = get_node_or_null("/root/Realm")
	if _realm != null:
		_realm.reset.connect(_on_realm_reset)
		_realm.agent_changed.connect(_on_agent_changed)
		_realm.task_changed.connect(_on_task_changed)
		_realm.approval_resolved.connect(_on_approval_resolved)
		_realm.incident_opened.connect(_on_incident_opened)
		_realm.mana_changed.connect(_on_mana_changed)
		_realm.age_changed.connect(_on_age_changed)
		_realm.changed.connect(_on_realm_changed)
	_game = get_node_or_null("/root/Game")
	if _game != null:
		_game.world_started.connect(_on_world_started)
		_game.world_stopped.connect(_on_world_stopped)
		if _game.get("world") != null:
			_on_world_started(null)


# --- public API ------------------------------------------------------------------------------

## Plays a named cue ("build_complete", "hand_bell", ...). Returns true when it started.
func play(cue: String) -> bool:
	return _play(cue, false, Vector3.ZERO)


## Plays a named cue at a point in the world ("construct_hit", "chop", "wall_rise", ...), heard
## from the camera. Returns true when it started.
func play_at(cue: String, position: Vector3) -> bool:
	return _play(cue, true, position)


## Web builds must unlock audio from a user gesture; the first click or key does it too.
func unlock() -> void:
	if unlocked:
		return
	unlocked = true
	set_process_input(false)


## True when the cue exists in the table and has at least one file.
func has_cue(cue: String) -> bool:
	return CueTable.CUES.has(cue) and not _files(cue).is_empty()


## Copies of `cue` playing now.
func voices_of(cue: String) -> int:
	var now := _now()
	var n := 0
	for v in _all_voices():
		if v.cue == cue and _active(v, now):
			n += 1
	return n


## Stops every cue (not the music or ambience).
func stop_all() -> void:
	for v in _all_voices():
		_free(v)


## Forgets cooldowns (tests, tools).
func reset_cooldowns() -> void:
	_next_allowed.clear()


## 0..1 slider value -> bus volume in dB (0 mutes).
static func volume_to_db(v: float) -> float:
	if v <= 0.0:
		return MUTE_DB
	return maxf(linear_to_db(minf(v, 1.0)), MUTE_DB)


## The gain (dB) that brings a file measured at `file_lufs` (peak momentary) to `target_lufs`,
## held so its true peak (`file_tp`, dBTP) stays at or below -1 dBTP.
static func file_gain(target_lufs: float, file_lufs: float, file_tp: float) -> float:
	return minf(target_lufs - file_lufs, -1.0 - file_tp)


# --- cues ------------------------------------------------------------------------------------

func _now() -> float:
	return Time.get_ticks_usec() / 1000000.0


func _files(cue: String) -> Array:
	var f: Variant = CueFiles.FILES.get(cue)
	return f if typeof(f) == TYPE_ARRAY else []


func _all_voices() -> Array[Voice]:
	var out: Array[Voice] = []
	out.append_array(_flat)
	out.append_array(_world)
	return out


func _active(v: Voice, now: float) -> bool:
	return v.cue != "" and now < v.ends and is_instance_valid(v.player)


func _free(v: Voice) -> void:
	if is_instance_valid(v.player):
		if v.world:
			(v.player as AudioStreamPlayer3D).stop()
		else:
			(v.player as AudioStreamPlayer).stop()
	v.cue = ""
	v.duck = 0.0


func _play(cue: String, at_world: bool, pos: Vector3) -> bool:
	if not enabled:
		return false
	var def := CueTable.get_cue(cue)
	if def.is_empty():
		_warn_once(cue, "Unknown sound cue \"%s\"." % cue)
		return false
	var files := _files(cue)
	if files.is_empty():
		_warn_once(cue, "Sound cue \"%s\" has no files (run scripts/fetch-audio.mjs)." % cue)
		return false
	if not unlocked:
		return false
	var now := _now()
	if now < float(_next_allowed.get(cue, 0.0)):
		return false
	var dist := 0.0
	if at_world:
		_ensure_world_pool()
		var ear: Variant = _ear()
		if ear != null:
			dist = pos.distance_to(ear as Vector3)
			if dist > float(def["range"]):
				return false
	var v := _take_voice(cue, def, at_world, pos, dist, now)
	if v == null:
		return false
	var entry: Array = _pick(cue, files)
	var stream := _stream(String(entry[0]))
	if stream == null:
		return false
	var vary := float(def["vary"])
	var spread := float(def["pitch"])
	# the random spread never pushes a file past -1 dBTP
	var gain := minf(float(def["lufs"]) - float(entry[1]) + _rng.randf_range(-vary, vary), -1.0 - float(entry[2]))
	var pitch := pow(2.0, _rng.randf_range(-spread, spread) / 12.0) if spread > 0.0 else 1.0
	var bus := StringName(String(def["bus"]))
	if v.world:
		var p := v.player as AudioStreamPlayer3D
		p.stream = stream
		p.bus = bus
		p.volume_db = gain + WORLD_DB
		p.pitch_scale = pitch
		p.global_position = pos
		if playback:
			p.play()
	else:
		var p := v.player as AudioStreamPlayer
		p.stream = stream
		p.bus = bus
		p.volume_db = gain
		p.pitch_scale = pitch
		if playback:
			p.play()
	v.cue = cue
	v.priority = int(def["priority"])
	v.started = now
	v.ends = now + stream.get_length() / pitch + 0.05
	v.duck = float(def["duck"])
	v.position = pos
	_next_allowed[cue] = now + float(def["cooldown"])
	if bool(def["click"]):
		_stand_in_frame = Engine.get_process_frames()
		if _click_pending:
			_click_superseded = true
	cue_played.emit(cue)
	return true


## A voice for the cue: within its voice limit, from the right pool, taking a lower-priority
## voice when the pool is full. Null when the cue must not play now.
func _take_voice(cue: String, def: Dictionary, at_world: bool, pos: Vector3, dist: float, now: float) -> Voice:
	var mine: Array[Voice] = []
	for v in _all_voices():
		if v.cue == cue and _active(v, now):
			mine.append(v)
	if mine.size() >= int(def["voices"]):
		var victim: Voice = null
		match String(def["steal"]):
			"oldest":
				for v in mine:
					if victim == null or v.started < victim.started:
						victim = v
			"far":
				var ear: Variant = _ear()
				if at_world and ear != null:
					var worst := dist
					for v in mine:
						var d := v.position.distance_to(ear as Vector3) if v.world else 0.0
						if d > worst:
							worst = d
							victim = v
		if victim == null:
			return null
		_free(victim)
		if victim.world == at_world:
			return victim
	var pool: Array[Voice] = _world if at_world else _flat
	for v in pool:
		if not _active(v, now) and is_instance_valid(v.player):
			return v
	# The pool is full: take the lowest-priority, oldest voice below this cue's priority (world
	# foley may also replace other foley).
	var prio := int(def["priority"])
	var best: Voice = null
	for v in pool:
		if v.priority < prio or (prio == 0 and v.priority == 0):
			if best == null or v.priority < best.priority or (v.priority == best.priority and v.started < best.started):
				best = v
	if best != null:
		_free(best)
	return best


## A random file of the cue, never the one it played last (when it has more than one).
## Tools may set _forced_variant to pick one.
func _pick(cue: String, files: Array) -> Array:
	var n := files.size()
	if _forced_variant >= 0:
		return files[mini(_forced_variant, n - 1)]
	var i := _rng.randi_range(0, n - 1)
	if n > 1 and i == int(_last_file.get(cue, -1)):
		i = (i + 1 + _rng.randi_range(0, n - 2)) % n
	_last_file[cue] = i
	return files[i]


func _stream(path: String) -> AudioStream:
	if _streams.has(path):
		return _streams[path]
	var s := load(path) as AudioStream
	if s == null:
		_warn_once(path, "Could not load the sound %s." % path)
	_streams[path] = s
	return s


func _warn_once(key: String, text: String) -> void:
	if _warned.has(key):
		return
	_warned[key] = true
	var log := get_node_or_null("/root/ClientLog")
	if log != null:
		log.warn("audio", text)
	else:
		push_warning(text)


# --- the world's ear ---------------------------------------------------------------------------

## The 3D pool lives under the WorldView (so its sounds share the camera's world and go with
## it), or under this node while there is none.
func _ensure_world_pool() -> void:
	var root: Node = null
	if _world_root != null:
		root = _world_root.get_ref() as Node
	if root == null or not root.is_inside_tree():
		root = self
	if _world_node != null and is_instance_valid(_world_node):
		if _world_node.get_parent() == root:
			return
		_world_node.queue_free()
	_world_node = Node3D.new()
	_world_node.name = "AudioWorld"
	root.add_child(_world_node)
	_listener = AudioListener3D.new()
	_listener.name = "Ear"
	_world_node.add_child(_listener)
	_world.clear()
	for i in POOL_WORLD:
		var p := AudioStreamPlayer3D.new()
		p.name = "Voice%d" % i
		p.unit_size = UNIT_SIZE
		p.max_db = 3.0
		p.panning_strength = PANNING
		# Godot's distance low-pass counts volume_db as distance, so quiet cues would come out
		# darker and quieter than the table says: distance is loudness alone here.
		p.attenuation_filter_db = 0.0
		_world_node.add_child(p)
		var v := Voice.new()
		v.player = p
		v.world = true
		_world.append(v)
	_update_ear()


## Where world sounds are heard from, or null without a camera.
func _ear() -> Variant:
	if _listener != null and is_instance_valid(_listener) and _listener.is_inside_tree() and _listener.is_current():
		return _listener.global_position
	var vp := get_viewport()
	var cam := vp.get_camera_3d() if vp != null else null
	return cam.global_position if cam != null else null


func _update_ear() -> void:
	if _listener == null or not is_instance_valid(_listener) or not _listener.is_inside_tree():
		return
	var cam := _listener.get_viewport().get_camera_3d()
	if cam == null:
		return
	var origin := cam.global_position
	var fwd := -cam.global_basis.z
	var ground := origin + fwd * 30.0
	if fwd.y < -0.05:
		ground = origin + fwd * (origin.y / -fwd.y)
	_listener.global_transform = Transform3D(cam.global_basis, ground.lerp(origin, LISTENER_LIFT))
	if not _listener.is_current():
		_listener.make_current()


# --- buses, focus and ducking ----------------------------------------------------------------------

func _setting(key: String, fallback: Variant) -> Variant:
	if _settings == null or not is_instance_valid(_settings):
		_settings = get_node_or_null("/root/Settings")
	return _settings.get_value(key, fallback) if _settings != null else fallback


func _on_setting_changed(key: String, _value: Variant) -> void:
	if key.begins_with("audio/"):
		_apply_volumes()


func _apply_volumes() -> void:
	var focus_db := linear_to_db(maxf(_focus_gain, 0.00001)) if _focus_gain < 0.9999 else 0.0
	for key: String in VOLUME_KEYS:
		var bus := AudioServer.get_bus_index(StringName(String(VOLUME_KEYS[key])))
		if bus < 0:
			continue
		var v := clampf(float(_setting(key, 1.0)), 0.0, 1.0)
		var vol := volume_to_db(v)
		match String(VOLUME_KEYS[key]):
			"Master":
				vol += focus_db
			"Music":
				vol -= _duck_db
			"Ambience":
				vol -= _duck_db * 0.5
		vol = maxf(vol, MUTE_DB)
		var mute := v <= 0.0
		if not is_equal_approx(float(_applied.get(key, 1.0e9)), vol) or AudioServer.is_bus_mute(bus) != mute:
			AudioServer.set_bus_volume_db(bus, vol)
			AudioServer.set_bus_mute(bus, mute)
			_applied[key] = vol


func _notification(what: int) -> void:
	match what:
		NOTIFICATION_APPLICATION_FOCUS_OUT:
			_focused = false
		NOTIFICATION_APPLICATION_FOCUS_IN:
			_focused = true
		NOTIFICATION_WM_CLOSE_REQUEST:
			# The game saves for a moment, then quits: stop now so no playback is left running.
			enabled = false
			stop_all()
			if _music != null:
				_music.stop()
				_amb_day.stop()
				_amb_night.stop()


func _input(event: InputEvent) -> void:
	if unlocked:
		return
	var press := (event is InputEventMouseButton or event is InputEventKey or event is InputEventScreenTouch) and event.is_pressed()
	if press:
		unlock()


func _process(delta: float) -> void:
	var now := _now()
	# focus fade
	var want_focus := 1.0
	if not _focused and bool(_setting("audio/mute_unfocused", true)):
		want_focus = db_to_linear(UNFOCUSED_DB)
	_focus_gain = lerpf(_focus_gain, want_focus, 1.0 - exp(-delta / FOCUS_FADE))
	if absf(_focus_gain - want_focus) < 0.0005:
		_focus_gain = want_focus
	# music ducking under bells and alerts
	var duck := 0.0
	for v in _all_voices():
		if v.duck > duck and _active(v, now):
			duck = v.duck
	var tau := DUCK_ATTACK if duck > _duck_db else DUCK_RELEASE
	_duck_db = lerpf(_duck_db, duck, 1.0 - exp(-delta / tau))
	if absf(_duck_db - duck) < 0.01:
		_duck_db = duck
	_apply_volumes()
	_update_ear()
	_update_ambience(delta)
	_update_music(delta, now)
	# load the cues' files a few per frame, so the first play of each is instant
	for i in 3:
		if _preload_queue.is_empty():
			break
		_stream(_preload_queue.pop_back())


# --- ambience -----------------------------------------------------------------------------------

func _has_world() -> bool:
	return _game != null and _game.get("world") != null


## The SkyEnvironment's night amount (0 day .. 1 night), read a few times a second.
func _night_amount() -> float:
	var sky: Node = _sky.get_ref() as Node if _sky != null else null
	if sky == null:
		return 0.0
	return clampf(float(sky.get("night")), 0.0, 1.0)


func _update_ambience(delta: float) -> void:
	var want := enabled and playback and unlocked and _has_world() and not CueFiles.AMBIENCE.is_empty()
	_amb_level = move_toward(_amb_level, 1.0 if want else 0.0, delta / AMBIENCE_FADE)
	_night_poll -= delta
	if _night_poll <= 0.0:
		_night_poll = 0.25
		_night = _night_amount()
	_bed(_amb_day, "day", cos(_night * PI * 0.5) * _amb_level)
	_bed(_amb_night, "night", sin(_night * PI * 0.5) * _amb_level)


func _bed(p: AudioStreamPlayer, which: String, lin: float) -> void:
	if lin <= 0.0005:
		if p.playing and not p.stream_paused:
			p.stream_paused = true
		return
	p.volume_db = linear_to_db(lin) + AMBIENCE_DB
	if p.stream == null:
		var bed: Dictionary = CueFiles.AMBIENCE.get(which, {})
		if bed.is_empty():
			return
		var s: AudioStream = _stream(String(bed.get("path", "")))
		if s == null:
			return
		if s is AudioStreamOggVorbis:
			(s as AudioStreamOggVorbis).loop = true
		p.stream = s
	if not p.playing:
		p.play(_rng.randf() * maxf(p.stream.get_length() - 1.0, 0.0))
	p.stream_paused = false


# --- music ----------------------------------------------------------------------------------------

func _update_music(delta: float, now: float) -> void:
	var want := enabled and playback and unlocked and _has_world() and not CueFiles.MUSIC.is_empty()
	if not want:
		if _music.playing and not _music_fading_out:
			_music_fading_out = true
		_music_next_at = -1.0
	elif _music_next_at < 0.0 and not _music.playing:
		_music_next_at = now + _rng.randf_range(MUSIC_FIRST_DELAY.x, MUSIC_FIRST_DELAY.y)
	if _music_fading_out:
		_music_gain = move_toward(_music_gain, 0.0, delta / MUSIC_FADE_OUT)
		if _music_gain <= 0.0:
			_music.stop()
			_music_fading_out = false
	elif _music.playing:
		_music_gain = move_toward(_music_gain, 1.0, delta / MUSIC_FADE_IN)
		if now > _music_ends:
			_on_music_finished()
	elif want and _music_next_at >= 0.0 and now >= _music_next_at:
		_start_track(now)
	_music.volume_db = linear_to_db(maxf(_music_gain, 0.00001)) + MUSIC_DB


func _start_track(now: float) -> void:
	if _music_order.is_empty():
		for i in CueFiles.MUSIC.size():
			_music_order.append(i)
		_music_order.shuffle()
	var idx: int = _music_order.pop_front()
	var track: Dictionary = CueFiles.MUSIC[idx]
	var s := _stream(String(track.get("path", "")))
	_music_next_at = -1.0
	if s == null:
		return
	_music.stream = s
	_music_gain = 0.0
	_music.play()
	_music_ends = now + s.get_length() + 2.0


func _on_music_finished() -> void:
	_music.stop()
	_music_next_at = _now() + _rng.randf_range(MUSIC_GAP.x, MUSIC_GAP.y)


## The track playing now ({path, title, author}), or {}.
func current_track() -> Dictionary:
	if not _music.playing or _music.stream == null:
		return {}
	for t: Dictionary in CueFiles.MUSIC:
		if String(t.get("path", "")) == _music.stream.resource_path:
			return t
	return {}


func _on_world_started(_w: Variant) -> void:
	_music_fading_out = false


func _on_world_stopped() -> void:
	# _update_music and _update_ambience fade both out once no world is left
	pass


# --- buttons and windows ----------------------------------------------------------------------------

## Script classes we watch for, matched by global name so this autoload does not load their
## scripts (and everything they reference) itself.
const WATCHED := ["WindowFrame", "WorldView"]


func _on_node_added(node: Node) -> void:
	if node is BaseButton:
		_hook_button(node as BaseButton)
		return
	if node is PopupMenu:
		if not node.has_meta("_audio"):
			node.set_meta("_audio", true)
			(node as PopupMenu).index_pressed.connect(_on_menu_pressed.bind(node))
		return
	if node is TabBar:
		if not node.has_meta("_audio"):
			node.set_meta("_audio", true)
			(node as TabBar).tab_clicked.connect(_on_tab_clicked.bind(node))
		return
	if node is WorldEnvironment:
		# The SkyEnvironment adds a WorldEnvironment as its child: that is our day and night.
		var sky := node.get_parent()
		if sky != null and "night" in sky:
			_sky = weakref(sky)
		return
	var script := node.get_script() as Script
	if script == null:
		return
	match _watched_class(script):
		"WindowFrame":
			_hook_window(node)
		"WorldView":
			_world_root = weakref(node)


static func _watched_class(script: Script) -> String:
	var s := script
	while s != null:
		var n := String(s.get_global_name())
		if n in WATCHED:
			return n
		s = s.get_base_script()
	return ""


func _hook_button(b: BaseButton) -> void:
	if b.has_meta("_audio"):
		return
	b.set_meta("_audio", true)
	b.pressed.connect(_on_button_pressed.bind(b))
	b.mouse_entered.connect(_on_button_hover.bind(b))


func _silent(c: Node) -> bool:
	return c == null or not is_instance_valid(c) or c.has_meta("audio_silent")


func _on_button_pressed(b: BaseButton) -> void:
	if _silent(b):
		return
	_queue_click()


func _on_menu_pressed(_index: int, menu: PopupMenu) -> void:
	if not _silent(menu):
		_queue_click()


func _on_tab_clicked(_tab: int, bar: TabBar) -> void:
	if not _silent(bar):
		_queue_click()


func _on_button_hover(b: BaseButton) -> void:
	if _silent(b) or b.disabled or not b.is_visible_in_tree():
		return
	play("ui_hover")


## The click plays at the end of the frame, unless the press already played a cue that stands
## in for it (ui_confirm, a command, ui_open...).
func _queue_click() -> void:
	if _click_pending:
		return
	_click_pending = true
	_click_superseded = _stand_in_frame == Engine.get_process_frames()
	_flush_click.call_deferred()


func _flush_click() -> void:
	_click_pending = false
	if _click_superseded:
		return
	play("ui_click")


func _hook_window(w: Node) -> void:
	if w.has_meta("_audio"):
		return
	w.set_meta("_audio", true)
	if w.has_signal("closed"):
		w.connect("closed", _on_window_closed.bind(w))
	if not _silent(w):
		play("ui_open")


func _on_window_closed(w: Node) -> void:
	if not _silent(w):
		play("ui_close")


# --- the Town Hall's news ---------------------------------------------------------------------------

## True while the running town is the Town Hall's (the agents' homes are in the world), or
## when a test says so (assume_town).
func _town_live() -> bool:
	if assume_town:
		return true
	return _realm != null and bool(_realm.get("has_state")) and _game != null and bool(_game.call("is_online_town"))


func _on_realm_reset() -> void:
	_ranks.clear()
	var agents: Dictionary = _realm.get("agents")
	for a: Dictionary in agents.values():
		_ranks[J.gs(a, "id")] = J.gs(a, "rank", "F")
	_parties.clear()
	var parties: Dictionary = _realm.get("parties")
	for id: String in parties:
		_parties[id] = true
	var mana: Dictionary = _realm.get("mana")
	_mana_level = J.gs(mana, "level")
	_mana_period = J.gs(mana, "period_start")
	var age: Dictionary = _realm.get("age")
	_age = J.gi(age, "current", 1)
	_researching = typeof(age.get("research")) == TYPE_DICTIONARY


func _on_agent_changed(agent: Dictionary) -> void:
	var id := J.gs(agent, "id")
	var rank := J.gs(agent, "rank", "F")
	var before := String(_ranks.get(id, ""))
	_ranks[id] = rank
	if before != "" and RANKS.find(rank) > RANKS.find(before) and _town_live():
		play("rank_up")


func _on_task_changed(task: Dictionary, previous_state: String) -> void:
	var state := J.gs(task, "state")
	if state == previous_state or not _town_live():
		return
	var sub := J.gs(task, "parent_task_id") != ""
	match state:
		"in_transit":
			if previous_state == "" and not sub:
				play("task_sent")
		"queued":
			if previous_state == "":
				if not sub:
					play("task_sent")
			elif previous_state == "in_transit":
				play("scroll_delivered")
			elif previous_state == "awaiting_review" or previous_state == "accepting":
				play("sent_back")
		"preparing":
			play("task_started")
		"running":
			if previous_state in ["queued", "in_transit", "paused", "failed"]:
				play("task_started")
		"failed":
			play("task_failed")


func _on_approval_resolved(_approval_id: String, info: Dictionary) -> void:
	# Only the player's own answers; rules and pre-approvals settle quietly.
	if J.gs(info, "by") != "player" or not _town_live():
		return
	play("approval_granted" if J.gs(info, "decision") == "allow" else "approval_denied")


func _on_incident_opened(incident: Dictionary) -> void:
	if not _town_live():
		return
	var kind := J.gs(incident, "kind")
	if kind == "hand_bell":
		# An approval's bell is TownLink's (it rings on approval_requested); a spent Mana Seal
		# has no approval, so it rings here.
		var task_id := J.gs(J.gd(incident, "subject"), "task_id")
		var approvals: Dictionary = _realm.get("approvals")
		for a: Dictionary in approvals.values():
			if J.gs(a, "task_id") == task_id:
				return
		play("hand_bell")
	elif INCIDENT_CUES.has(kind):
		play(String(INCIDENT_CUES[kind]))


func _on_mana_changed(mana: Dictionary) -> void:
	var level := J.gs(mana, "level")
	var period := J.gs(mana, "period_start")
	if level == "":
		return
	var before := _mana_level
	var before_period := _mana_period
	_mana_level = level
	_mana_period = period
	if before == "" or not _town_live():
		return
	var worse := MANA_LEVELS.find(level) - MANA_LEVELS.find(before)
	if (period != before_period and before_period != "") or (worse < 0 and level == "normal"):
		play("dawn_bell")
	elif worse > 0:
		match level:
			"dim":
				play("lanterns_dim")
			"warning":
				play("warning_bell")


func _on_age_changed(age: Dictionary) -> void:
	var current := J.gi(age, "current", 1)
	var researching := typeof(age.get("research")) == TYPE_DICTIONARY
	var before_age := _age
	var before_research := _researching
	_age = current
	_researching = researching
	if before_age == 0 or not _town_live():
		return
	if current > before_age:
		play("age_bells")
	elif researching and not before_research:
		play("research_start")


func _on_realm_changed(kind: String, id: String) -> void:
	if kind != "party" or id == "":
		return
	var parties: Dictionary = _realm.get("parties")
	if not parties.has(id):
		_parties.erase(id)
		return
	if _parties.has(id):
		return
	_parties[id] = true
	if _town_live():
		play("party_formed")
