extends RefCounted
## The mix: how loud, how often and how many of each cue may play. The files behind each cue
## (and their measured loudness) are in cue_files.gd, generated by scripts/fetch-audio.mjs.
##
## Fields (anything left out takes DEFAULTS):
##   bus       "UI" or "SFX" (music and ambience have their own players and buses)
##   lufs      how loud the cue plays with every volume slider at 1 (peak momentary loudness,
##             LUFS); the Audio autoload derives each file's gain from its measured loudness
##   vary      random volume spread, +/- dB
##   pitch     random pitch spread, +/- semitones (0 for anything tuned: bells, chimes, plucks)
##   cooldown  seconds before the cue can play again, so a busy town never machine-guns
##   voices    most copies of the cue playing at once
##   priority  0 world foley, 1 feedback, 2 notices, 3 bells and alerts; a full pool takes a
##             voice from a lower priority, never a higher one
##   steal     at the voice limit: "" drops the new sound, "oldest" restarts the oldest copy,
##             "far" replaces the copy farthest from the listener (world sounds) when it is nearer
##   duck      dB the music dips while the cue plays (the ambience dips half as much)
##   click     true for cues a button press triggers: they stand in for that press's ui_click
##   range     world sounds: farther from the listener than this (tiles), the cue is not played

## The cue names every workstream calls (Audio.play / Audio.play_at). Each must resolve to at
## least one file (tests/unit/test_audio.gd checks).
const CANONICAL := [
	# UI
	"ui_click", "ui_hover", "ui_open", "ui_close", "ui_confirm", "ui_error",
	# Commands
	"select_townsfolk", "select_agent", "select_building", "command_move", "command_gather",
	"command_build", "placement_ok", "placement_bad",
	# Town
	"build_start", "construct_hit", "build_complete", "train_complete", "summon", "need_houses",
	"chop", "gather_food", "drop_off", "wisp", "scroll_delivered",
	# Agents
	"task_sent", "task_started", "task_done", "reward", "sent_back", "task_failed", "hand_bell",
	"approval_granted", "approval_denied", "rank_up", "party_formed",
	# Alerts
	"alarm_bell", "warning_bell", "dawn_bell", "lanterns_dim", "font_dark", "rift", "smoke",
	# Ages and trade
	"research_start", "wall_rise", "age_bells", "trade",
]

const DEFAULTS := {
	"bus": "SFX", "lufs": -22.0, "vary": 1.0, "pitch": 0.0, "cooldown": 0.05, "voices": 2,
	"priority": 1, "steal": "", "duck": 0.0, "click": false, "range": 60.0,
}

const CUES := {
	# --- UI: quiet, quick, never in the way -----------------------------------------------------
	"ui_click": {"bus": "UI", "lufs": -27.0, "pitch": 0.5, "cooldown": 0.035, "voices": 2, "steal": "oldest"},
	"ui_hover": {"bus": "UI", "lufs": -37.0, "vary": 1.5, "pitch": 0.7, "cooldown": 0.06, "voices": 1,
		"priority": 0, "steal": "oldest"},
	"ui_open": {"bus": "UI", "lufs": -26.0, "pitch": 0.6, "cooldown": 0.1, "voices": 2, "click": true},
	"ui_close": {"bus": "UI", "lufs": -27.0, "pitch": 0.6, "cooldown": 0.1, "voices": 2, "click": true},
	"ui_confirm": {"bus": "UI", "lufs": -23.0, "vary": 0.5, "cooldown": 0.12, "voices": 1, "click": true},
	"ui_error": {"bus": "UI", "lufs": -23.0, "vary": 0.5, "cooldown": 0.25, "voices": 1, "click": true},

	# --- Commands: the town answers an order ----------------------------------------------------
	"select_townsfolk": {"bus": "UI", "lufs": -26.0, "pitch": 1.0, "cooldown": 0.08, "voices": 1, "steal": "oldest", "click": true},
	"select_agent": {"bus": "UI", "lufs": -25.0, "vary": 0.5, "cooldown": 0.08, "voices": 1, "steal": "oldest", "click": true},
	"select_building": {"bus": "UI", "lufs": -26.0, "pitch": 0.8, "cooldown": 0.08, "voices": 1, "steal": "oldest", "click": true},
	"command_move": {"bus": "UI", "lufs": -26.0, "pitch": 0.8, "cooldown": 0.12, "voices": 1, "steal": "oldest", "click": true},
	"command_gather": {"bus": "UI", "lufs": -26.0, "pitch": 0.8, "cooldown": 0.12, "voices": 1, "steal": "oldest", "click": true},
	"command_build": {"bus": "UI", "lufs": -25.0, "pitch": 0.8, "cooldown": 0.12, "voices": 1, "steal": "oldest", "click": true},
	"placement_ok": {"bus": "UI", "lufs": -23.0, "pitch": 0.6, "cooldown": 0.1, "voices": 2, "click": true},
	"placement_bad": {"bus": "UI", "lufs": -24.0, "vary": 0.5, "cooldown": 0.25, "voices": 1, "click": true},

	# --- Town: world foley (placed in the world) and the town's own news ------------------------
	"build_start": {"lufs": -23.0, "pitch": 0.8, "cooldown": 0.3, "voices": 2},
	"construct_hit": {"lufs": -24.0, "vary": 2.0, "pitch": 1.2, "cooldown": 0.09, "voices": 4, "priority": 0,
		"steal": "far", "range": 55.0},
	"build_complete": {"lufs": -20.0, "vary": 0.5, "cooldown": 0.6, "voices": 2, "priority": 2, "duck": 2.0},
	"train_complete": {"lufs": -21.0, "vary": 0.5, "cooldown": 0.6, "voices": 2, "priority": 2},
	"summon": {"lufs": -18.0, "vary": 0.5, "cooldown": 1.0, "voices": 1, "priority": 2, "duck": 4.0, "click": true},
	"need_houses": {"lufs": -21.0, "vary": 0.5, "cooldown": 8.0, "voices": 1, "priority": 2},
	"chop": {"lufs": -24.0, "vary": 2.0, "pitch": 1.0, "cooldown": 0.1, "voices": 3, "priority": 0,
		"steal": "far", "range": 50.0},
	"gather_food": {"lufs": -28.0, "vary": 2.0, "pitch": 1.0, "cooldown": 0.15, "voices": 2, "priority": 0,
		"steal": "far", "range": 40.0},
	"drop_off": {"lufs": -25.0, "vary": 1.5, "pitch": 0.8, "cooldown": 0.2, "voices": 2, "priority": 0,
		"steal": "far", "range": 50.0},
	"wisp": {"lufs": -24.0, "vary": 1.0, "pitch": 0.5, "cooldown": 0.4, "voices": 2, "priority": 0, "steal": "far"},
	"scroll_delivered": {"lufs": -24.0, "vary": 0.5, "cooldown": 0.4, "voices": 2},

	# --- Agents: their work, your answers --------------------------------------------------------
	"task_sent": {"lufs": -23.0, "vary": 0.5, "cooldown": 0.4, "voices": 1, "click": true},
	"task_started": {"lufs": -24.0, "vary": 0.5, "cooldown": 0.6, "voices": 2},
	"task_done": {"lufs": -19.0, "vary": 0.5, "cooldown": 0.8, "voices": 1, "priority": 2, "duck": 2.0},
	"reward": {"lufs": -18.0, "vary": 0.5, "cooldown": 1.5, "voices": 1, "priority": 2, "duck": 3.0},
	"sent_back": {"lufs": -22.0, "vary": 0.5, "cooldown": 0.5, "voices": 1, "priority": 2},
	"task_failed": {"lufs": -20.0, "vary": 0.5, "cooldown": 1.0, "voices": 1, "priority": 2},
	"hand_bell": {"lufs": -18.0, "vary": 0.5, "cooldown": 1.2, "voices": 1, "priority": 3, "duck": 3.0},
	"approval_granted": {"lufs": -21.0, "vary": 0.5, "cooldown": 0.3, "voices": 2, "priority": 2},
	"approval_denied": {"lufs": -21.0, "vary": 0.5, "cooldown": 0.3, "voices": 2, "priority": 2},
	"rank_up": {"lufs": -17.0, "vary": 0.0, "cooldown": 2.0, "voices": 1, "priority": 2, "duck": 5.0},
	"party_formed": {"lufs": -19.0, "vary": 0.0, "cooldown": 2.0, "voices": 1, "priority": 2, "duck": 3.0},

	# --- Alerts: each one unmistakable -------------------------------------------------------------
	"alarm_bell": {"lufs": -15.0, "vary": 0.0, "cooldown": 4.0, "voices": 1, "priority": 3, "duck": 8.0},
	"warning_bell": {"lufs": -16.0, "vary": 0.0, "cooldown": 8.0, "voices": 1, "priority": 3, "duck": 8.0},
	"dawn_bell": {"lufs": -18.0, "vary": 0.0, "cooldown": 8.0, "voices": 1, "priority": 3, "duck": 6.0},
	"lanterns_dim": {"lufs": -20.0, "vary": 0.0, "cooldown": 5.0, "voices": 1, "priority": 3, "duck": 3.0},
	"font_dark": {"lufs": -17.0, "vary": 0.0, "cooldown": 5.0, "voices": 1, "priority": 3, "duck": 6.0},
	"rift": {"lufs": -19.0, "vary": 0.5, "cooldown": 2.0, "voices": 1, "priority": 3, "duck": 4.0},
	"smoke": {"lufs": -22.0, "vary": 1.0, "cooldown": 1.5, "voices": 2, "priority": 2},

	# --- Ages and trade ------------------------------------------------------------------------------
	"research_start": {"lufs": -20.0, "vary": 0.0, "cooldown": 2.0, "voices": 1, "priority": 2, "duck": 3.0},
	"wall_rise": {"lufs": -20.0, "vary": 1.5, "pitch": 1.0, "cooldown": 0.2, "voices": 3, "priority": 1,
		"steal": "far", "range": 80.0},
	"age_bells": {"lufs": -14.0, "vary": 0.0, "cooldown": 10.0, "voices": 1, "priority": 3, "duck": 10.0},
	"trade": {"bus": "UI", "lufs": -23.0, "pitch": 0.6, "cooldown": 0.15, "voices": 2, "click": true},
}


## The cue's settings with every default filled in, or {} for an unknown cue.
static func get_cue(cue: String) -> Dictionary:
	var c: Variant = CUES.get(cue)
	if typeof(c) != TYPE_DICTIONARY:
		return {}
	var out: Dictionary = DEFAULTS.duplicate()
	out.merge(c as Dictionary, true)
	return out
