# Generated by scripts/fetch-audio.mjs. Do not edit by hand: rerun the script.
# FILES: cue -> [[path, peak momentary loudness in LUFS, true peak in dBTP], ...]; one file is
# picked at random each time. MUSIC: the playlist. AMBIENCE: the day and night beds (seamless
# loops). The music and beds carry their integrated loudness in LUFS.
extends RefCounted

const FILES := {
	"age_bells": [["res://audio/ages/age_bells.ogg", -16.0, -7.0]],
	"alarm_bell": [["res://audio/alerts/alarm_bell.ogg", -16.0, -5.6]],
	"approval_denied": [["res://audio/agents/approval_denied.ogg", -16.0, -3.7]],
	"approval_granted": [["res://audio/agents/approval_granted.ogg", -15.9, -8.1]],
	"build_complete": [["res://audio/town/build_complete.ogg", -16.1, -6.5]],
	"build_start": [["res://audio/town/build_start_1.wav", -16.0, -1.8], ["res://audio/town/build_start_2.wav", -16.0, -1.1]],
	"chop": [["res://audio/town/chop_1.wav", -17.8, -1.0], ["res://audio/town/chop_2.wav", -17.6, -1.4], ["res://audio/town/chop_3.wav", -17.6, -1.0], ["res://audio/town/chop_4.wav", -17.6, -1.5]],
	"command_build": [["res://audio/commands/command_build_1.wav", -16.0, -2.5], ["res://audio/commands/command_build_2.wav", -16.0, -1.3]],
	"command_gather": [["res://audio/commands/command_gather_1.wav", -19.6, -2.5], ["res://audio/commands/command_gather_2.wav", -19.6, -1.0]],
	"command_move": [["res://audio/commands/command_move_1.wav", -19.3, -1.0], ["res://audio/commands/command_move_2.wav", -19.6, -1.0], ["res://audio/commands/command_move_3.wav", -19.3, -1.1]],
	"construct_hit": [["res://audio/town/construct_hit_1.wav", -18.9, -1.0], ["res://audio/town/construct_hit_2.wav", -17.5, -1.7], ["res://audio/town/construct_hit_3.wav", -17.5, -1.1], ["res://audio/town/construct_hit_4.wav", -17.5, -1.0], ["res://audio/town/construct_hit_5.wav", -20.7, -1.0]],
	"dawn_bell": [["res://audio/alerts/dawn_bell.ogg", -15.9, -4.0]],
	"drop_off": [["res://audio/town/drop_off_1.wav", -16.0, -1.1], ["res://audio/town/drop_off_2.wav", -16.0, -2.5], ["res://audio/town/drop_off_3.wav", -16.0, -1.3]],
	"font_dark": [["res://audio/alerts/font_dark.ogg", -16.0, -8.4]],
	"gather_food": [["res://audio/town/gather_food_1.wav", -21.9, -1.4], ["res://audio/town/gather_food_2.wav", -21.9, -3.3], ["res://audio/town/gather_food_3.wav", -22.1, -1.0], ["res://audio/town/gather_food_4.wav", -21.9, -1.0]],
	"hand_bell": [["res://audio/agents/hand_bell_1.ogg", -16.0, -7.2], ["res://audio/agents/hand_bell_2.ogg", -16.0, -9.4]],
	"lanterns_dim": [["res://audio/alerts/lanterns_dim.ogg", -16.0, -6.1]],
	"need_houses": [["res://audio/town/need_houses.ogg", -16.0, -6.3]],
	"party_formed": [["res://audio/agents/party_formed.ogg", -16.0, -8.1]],
	"placement_bad": [["res://audio/commands/placement_bad.wav", -18.7, -1.0]],
	"placement_ok": [["res://audio/commands/placement_ok_1.wav", -19.0, -2.4], ["res://audio/commands/placement_ok_2.wav", -19.0, -1.0]],
	"rank_up": [["res://audio/agents/rank_up.ogg", -16.0, -9.2]],
	"research_start": [["res://audio/ages/research_start.ogg", -16.0, -7.2]],
	"reward": [["res://audio/agents/reward.ogg", -16.1, -7.0]],
	"rift": [["res://audio/alerts/rift.ogg", -16.0, -3.0]],
	"scroll_delivered": [["res://audio/town/scroll_delivered.ogg", -18.3, -1.1]],
	"select_agent": [["res://audio/commands/select_agent_1.ogg", -16.0, -6.7], ["res://audio/commands/select_agent_2.ogg", -16.1, -7.9], ["res://audio/commands/select_agent_3.ogg", -15.9, -6.1]],
	"select_building": [["res://audio/commands/select_building_1.wav", -20.4, -1.0], ["res://audio/commands/select_building_2.wav", -20.4, -2.0], ["res://audio/commands/select_building_3.wav", -20.4, -1.0]],
	"select_townsfolk": [["res://audio/commands/select_townsfolk_1.wav", -19.2, -1.0], ["res://audio/commands/select_townsfolk_2.wav", -19.5, -1.0], ["res://audio/commands/select_townsfolk_3.wav", -19.2, -3.4]],
	"sent_back": [["res://audio/agents/sent_back.ogg", -18.6, -1.4]],
	"smoke": [["res://audio/alerts/smoke.ogg", -16.1, -4.7]],
	"summon": [["res://audio/town/summon.ogg", -15.9, -8.6]],
	"task_done": [["res://audio/agents/task_done.ogg", -15.9, -8.8]],
	"task_failed": [["res://audio/agents/task_failed.ogg", -16.0, -4.5]],
	"task_sent": [["res://audio/agents/task_sent.ogg", -19.5, -0.9]],
	"task_started": [["res://audio/agents/task_started.ogg", -16.0, -7.0]],
	"trade": [["res://audio/ages/trade_1.wav", -21.3, -3.7], ["res://audio/ages/trade_2.wav", -21.3, -1.0]],
	"train_complete": [["res://audio/town/train_complete.ogg", -16.0, -4.6]],
	"ui_click": [["res://audio/ui/ui_click_1.wav", -23.6, -2.2], ["res://audio/ui/ui_click_2.wav", -23.6, -1.0], ["res://audio/ui/ui_click_3.wav", -27.0, -1.0]],
	"ui_close": [["res://audio/ui/ui_close_1.wav", -22.1, -1.0], ["res://audio/ui/ui_close_2.wav", -22.1, -3.8]],
	"ui_confirm": [["res://audio/ui/ui_confirm.ogg", -17.3, -1.3]],
	"ui_error": [["res://audio/ui/ui_error.wav", -16.0, -2.6]],
	"ui_hover": [["res://audio/ui/ui_hover_1.wav", -22.1, -1.0], ["res://audio/ui/ui_hover_2.wav", -22.1, -5.4]],
	"ui_open": [["res://audio/ui/ui_open_1.wav", -24.2, -2.4], ["res://audio/ui/ui_open_2.wav", -24.2, -1.0]],
	"wall_rise": [["res://audio/ages/wall_rise_1.ogg", -16.1, -5.6], ["res://audio/ages/wall_rise_2.ogg", -16.1, -2.3], ["res://audio/ages/wall_rise_3.ogg", -16.0, -2.7]],
	"warning_bell": [["res://audio/alerts/warning_bell.ogg", -16.0, -6.6]],
	"wisp": [["res://audio/town/wisp_1.ogg", -16.0, -9.4], ["res://audio/town/wisp_2.ogg", -16.0, -9.4]],
}

const MUSIC := [
	{"path": "res://audio/music/bards_tale.ogg", "title": "Medieval: The Bard's Tale", "author": "RandomMind", "lufs": -18.0},
	{"path": "res://audio/music/town_theme.ogg", "title": "Town Theme RPG", "author": "cynicmusic", "lufs": -18.1},
	{"path": "res://audio/music/exploration.ogg", "title": "Medieval: Exploration", "author": "RandomMind", "lufs": -18.1},
	{"path": "res://audio/music/calm_town.ogg", "title": "Calming RPG Town Theme", "author": "Destin715", "lufs": -18.0},
]

const AMBIENCE := {
	"day": {"path": "res://audio/ambience/day.ogg", "lufs": -24.1},
	"night": {"path": "res://audio/ambience/night.ogg", "lufs": -24.3},
}
