/**
 * Writes protocol/generated/protocol.gd: GDScript constants for message types, error codes and
 * enums, taken from the Town Hall's zod schemas so the Godot client never drifts from them.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { z } from "zod";
import { TERMINAL_STATES } from "../src/core/tasks/state-machine.js";
import { generatedGdPath } from "../src/paths.js";
import {
  ActivityKind,
  AgentActivity,
  AgentLifecycle,
  ApprovalCategory,
  ApprovalDecision,
  ApprovalMode,
  ApprovalResolvedBy,
  ApprovalScope,
  ApprovalStatus,
  Billing,
  BillingHint,
  BlockedReason,
  Catchup,
  ClientPlatform,
  CloseCode,
  COMMAND_TYPES,
  CourierMode,
  DiffFileStatus,
  ENVELOPE_VERSION,
  ErrorCode,
  EVENT_TYPES,
  HELLO_TIMEOUT_MS,
  IncidentKind,
  IncidentSeverity,
  Integrate,
  ManaLevel,
  ManaPeriod,
  MAX_FRAME_BYTES,
  MergeBlockedReason,
  MilestoneKey,
  PauseReason,
  ProgressPhase,
  PROTOCOL_MAJOR,
  PROTOCOL_MINOR,
  Provider,
  ResourceName,
  RetireWhen,
  Risk,
  Role,
  SettingKey,
  TaskSize,
  TaskState,
  ToolStatus,
  ToolType,
  WaygateTransport,
  WorkspaceMode,
} from "../src/protocol/index.js";

type AnyEnum = z.ZodEnum<Record<string, string>>;

const ENUMS: Array<[string, AnyEnum, string]> = [
  ["TaskState", TaskState as unknown as AnyEnum, "Task.state"],
  ["PauseReason", PauseReason as unknown as AnyEnum, "Task.state_reason when paused"],
  ["TaskSize", TaskSize as unknown as AnyEnum, "Task.size"],
  ["CourierMode", CourierMode as unknown as AnyEnum, "Task.courier.mode"],
  ["ProgressPhase", ProgressPhase as unknown as AnyEnum, "task_progress.phase"],
  ["ActivityKind", ActivityKind as unknown as AnyEnum, "task_activity entry.kind"],
  ["AgentLifecycle", AgentLifecycle as unknown as AnyEnum, "Agent.lifecycle"],
  ["AgentActivity", AgentActivity as unknown as AnyEnum, "Agent.activity"],
  ["BlockedReason", BlockedReason as unknown as AnyEnum, "Agent.blocked_reason"],
  ["Role", Role as unknown as AnyEnum, "Agent.role"],
  ["Provider", Provider as unknown as AnyEnum, "Agent.provider"],
  ["ApprovalMode", ApprovalMode as unknown as AnyEnum, "Agent.approval_mode"],
  ["WorkspaceMode", WorkspaceMode as unknown as AnyEnum, "Agent.workspace.mode"],
  ["Billing", Billing as unknown as AnyEnum, "Agent.billing"],
  ["BillingHint", BillingHint as unknown as AnyEnum, "check_providers billing_hint"],
  ["ToolType", ToolType as unknown as AnyEnum, "ToolAddon.type"],
  ["ToolStatus", ToolStatus as unknown as AnyEnum, "ToolAddon.status"],
  ["WaygateTransport", WaygateTransport as unknown as AnyEnum, "Waygate config transport"],
  ["ApprovalCategory", ApprovalCategory as unknown as AnyEnum, "Approval.category"],
  ["ApprovalStatus", ApprovalStatus as unknown as AnyEnum, "Approval.status"],
  ["ApprovalScope", ApprovalScope as unknown as AnyEnum, "Approval.scopes / respond_approval scope"],
  ["ApprovalDecision", ApprovalDecision as unknown as AnyEnum, "respond_approval decision"],
  ["ApprovalResolvedBy", ApprovalResolvedBy as unknown as AnyEnum, "approval_resolved.by"],
  ["Risk", Risk as unknown as AnyEnum, "Approval.risk"],
  ["IncidentKind", IncidentKind as unknown as AnyEnum, "Incident.kind"],
  ["IncidentSeverity", IncidentSeverity as unknown as AnyEnum, "Incident.severity"],
  ["ManaLevel", ManaLevel as unknown as AnyEnum, "Mana.level"],
  ["ManaPeriod", ManaPeriod as unknown as AnyEnum, "Mana.period"],
  ["Integrate", Integrate as unknown as AnyEnum, "accept_result integrate"],
  ["MergeBlockedReason", MergeBlockedReason as unknown as AnyEnum, "accept_result merge.blocked_reason"],
  ["DiffFileStatus", DiffFileStatus as unknown as AnyEnum, "get_task_detail diff.files[].status"],
  ["Catchup", Catchup as unknown as AnyEnum, "hello_result catchup"],
  ["ClientPlatform", ClientPlatform as unknown as AnyEnum, "hello client.platform"],
  ["RetireWhen", RetireWhen as unknown as AnyEnum, "retire_agent when"],
  ["ResourceName", ResourceName as unknown as AnyEnum, "resource keys"],
  ["SettingKey", SettingKey as unknown as AnyEnum, "set_setting key"],
  ["MilestoneKey", MilestoneKey as unknown as AnyEnum, "Progress next.milestones[].key (1.3)"],
];

function constName(value: string): string {
  const name = value.toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return /^[0-9]/.test(name) ? `V_${name}` : name;
}

function quote(s: string): string {
  return JSON.stringify(s);
}

function list(values: readonly string[]): string {
  return `[${values.map(quote).join(", ")}]`;
}

export function renderGd(): string {
  const out: string[] = [];
  out.push("# Generated by townhall/scripts/gen-gd.ts from the Town Hall's zod schemas. Do not edit by hand.");
  out.push("# Regenerate with: cd townhall && npm run gen:gd");
  out.push('# Usage: const Protocol = preload("res://<path>/protocol.gd"), then Protocol.CMD_HELLO or Protocol.TaskState.RUNNING.');
  out.push("extends RefCounted");
  out.push("");
  out.push(`const PROTOCOL_MAJOR := ${PROTOCOL_MAJOR}`);
  out.push(`const PROTOCOL_MINOR := ${PROTOCOL_MINOR}`);
  out.push(`const ENVELOPE_VERSION := ${ENVELOPE_VERSION}`);
  out.push(`const MAX_FRAME_BYTES := ${MAX_FRAME_BYTES}`);
  out.push(`const HELLO_TIMEOUT_MS := ${HELLO_TIMEOUT_MS}`);
  out.push("");
  out.push("# WebSocket close codes");
  for (const [k, v] of Object.entries(CloseCode)) out.push(`const CLOSE_${k} := ${v}`);
  out.push("");
  out.push('# Commands (client to server). Each reply is the command name plus "_result".');
  for (const c of COMMAND_TYPES) out.push(`const CMD_${constName(c)} := ${quote(c)}`);
  out.push(`const COMMANDS := ${list(COMMAND_TYPES)}`);
  out.push("");
  out.push("# Events (server to client)");
  for (const e of EVENT_TYPES) out.push(`const EVT_${constName(e)} := ${quote(e)}`);
  out.push(`const EVENTS := ${list(EVENT_TYPES)}`);
  out.push("");
  out.push("# Error codes");
  for (const e of ErrorCode.options) out.push(`const ERR_${constName(e)} := ${quote(e)}`);
  out.push(`const ERROR_CODES := ${list(ErrorCode.options)}`);
  out.push("");
  out.push(`const TERMINAL_TASK_STATES := ${list(TERMINAL_STATES)}`);
  for (const [name, schema, doc] of ENUMS) {
    const values = schema.options as readonly string[];
    out.push("");
    out.push(`# ${doc}`);
    out.push(`class ${name}:`);
    for (const v of values) out.push(`\tconst ${constName(v)} := ${quote(v)}`);
    out.push(`\tconst ALL := ${list(values)}`);
  }
  out.push("");
  return out.join("\n");
}

function main(): void {
  const target = process.argv[2] ? path.resolve(process.argv[2]) : generatedGdPath();
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, renderGd(), "utf8");
  process.stdout.write(`wrote ${target}\n`);
}

const invokedDirectly = process.argv[1] && path.resolve(process.argv[1]).replace(/\.[cm]?[jt]s$/, "") === path.resolve(import.meta.filename).replace(/\.[cm]?[jt]s$/, "");
if (invokedDirectly) main();
