# Generated by townhall/scripts/gen-gd.ts from the Town Hall's zod schemas. Do not edit by hand.
# Regenerate with: cd townhall && npm run gen:gd
# Usage: const Protocol = preload("res://<path>/protocol.gd"), then Protocol.CMD_HELLO or Protocol.TaskState.RUNNING.
extends RefCounted

const PROTOCOL_MAJOR := 1
const PROTOCOL_MINOR := 2
const ENVELOPE_VERSION := 1
const MAX_FRAME_BYTES := 1048576
const HELLO_TIMEOUT_MS := 5000

# WebSocket close codes
const CLOSE_BAD_TOKEN := 4001
const CLOSE_NO_HELLO := 4002
const CLOSE_PROTOCOL_MISMATCH := 4400
const CLOSE_REPLACED := 4409

# Commands (client to server). Each reply is the command name plus "_result".
const CMD_HELLO := "hello"
const CMD_PING := "ping"
const CMD_GET_STATE := "get_state"
const CMD_CHECK_PROVIDERS := "check_providers"
const CMD_LIST_MODELS := "list_models"
const CMD_BROWSE_FOLDER := "browse_folder"
const CMD_CREATE_AGENT := "create_agent"
const CMD_AGENT_TRAINED := "agent_trained"
const CMD_PLACE_HOME := "place_home"
const CMD_HOME_BUILT := "home_built"
const CMD_UPDATE_AGENT := "update_agent"
const CMD_RETIRE_AGENT := "retire_agent"
const CMD_ATTACH_TOOL := "attach_tool"
const CMD_TOOL_BUILT := "tool_built"
const CMD_DETACH_TOOL := "detach_tool"
const CMD_ASSIGN_TASK := "assign_task"
const CMD_TASK_DELIVERED := "task_delivered"
const CMD_CANCEL_TASK := "cancel_task"
const CMD_RESUME_TASK := "resume_task"
const CMD_STOP_AND_REVIEW := "stop_and_review"
const CMD_NUDGE_TASK := "nudge_task"
const CMD_RESPOND_APPROVAL := "respond_approval"
const CMD_GET_TASK_DETAIL := "get_task_detail"
const CMD_ACCEPT_RESULT := "accept_result"
const CMD_SEND_BACK := "send_back"
const CMD_ABANDON_TASK := "abandon_task"
const CMD_DISCARD_WORKSPACE := "discard_workspace"
const CMD_FORM_PARTY := "form_party"
const CMD_DISBAND_PARTY := "disband_party"
const CMD_SET_BUDGET := "set_budget"
const CMD_SPEND_RESOURCES := "spend_resources"
const CMD_REFUND_RESOURCES := "refund_resources"
const CMD_REPORT_GATHER := "report_gather"
const CMD_TRADE := "trade"
const CMD_ADVANCE_AGE := "advance_age"
const CMD_SAVE_TOWN := "save_town"
const CMD_LOAD_TOWN := "load_town"
const CMD_SET_SETTING := "set_setting"
const CMD_GET_LEDGER := "get_ledger"
const COMMANDS := ["hello", "ping", "get_state", "check_providers", "list_models", "browse_folder", "create_agent", "agent_trained", "place_home", "home_built", "update_agent", "retire_agent", "attach_tool", "tool_built", "detach_tool", "assign_task", "task_delivered", "cancel_task", "resume_task", "stop_and_review", "nudge_task", "respond_approval", "get_task_detail", "accept_result", "send_back", "abandon_task", "discard_workspace", "form_party", "disband_party", "set_budget", "spend_resources", "refund_resources", "report_gather", "trade", "advance_age", "save_town", "load_town", "set_setting", "get_ledger"]

# Events (server to client)
const EVT_AGENT_UPDATED := "agent_updated"
const EVT_AGENT_RETIRED := "agent_retired"
const EVT_TOOL_UPDATED := "tool_updated"
const EVT_TASK_UPDATED := "task_updated"
const EVT_TASK_PROGRESS := "task_progress"
const EVT_TASK_ACTIVITY := "task_activity"
const EVT_APPROVAL_REQUESTED := "approval_requested"
const EVT_APPROVAL_RESOLVED := "approval_resolved"
const EVT_MANA_UPDATED := "mana_updated"
const EVT_TREASURY_UPDATED := "treasury_updated"
const EVT_INCIDENT_OPENED := "incident_opened"
const EVT_INCIDENT_RESOLVED := "incident_resolved"
const EVT_PARTY_UPDATED := "party_updated"
const EVT_PARTY_DISBANDED := "party_disbanded"
const EVT_SUBTASK_DELEGATED := "subtask_delegated"
const EVT_AGE_UPDATED := "age_updated"
const EVT_PROVIDERS_UPDATED := "providers_updated"
const EVT_TOWN_SAVED := "town_saved"
const EVT_SESSION_REVOKED := "session_revoked"
const EVT_DAEMON_SHUTDOWN := "daemon_shutdown"
const EVENTS := ["agent_updated", "agent_retired", "tool_updated", "task_updated", "task_progress", "task_activity", "approval_requested", "approval_resolved", "mana_updated", "treasury_updated", "incident_opened", "incident_resolved", "party_updated", "party_disbanded", "subtask_delegated", "age_updated", "providers_updated", "town_saved", "session_revoked", "daemon_shutdown"]

# Error codes
const ERR_AUTH_FAILED := "AUTH_FAILED"
const ERR_BAD_REQUEST := "BAD_REQUEST"
const ERR_NOT_FOUND := "NOT_FOUND"
const ERR_INSUFFICIENT_RESOURCES := "INSUFFICIENT_RESOURCES"
const ERR_INSUFFICIENT_MANA := "INSUFFICIENT_MANA"
const ERR_AGE_REQUIRED := "AGE_REQUIRED"
const ERR_RANK_REQUIRED := "RANK_REQUIRED"
const ERR_LIMIT_REACHED := "LIMIT_REACHED"
const ERR_INVALID_STATE := "INVALID_STATE"
const ERR_CONFLICT := "CONFLICT"
const ERR_PROVIDER_UNAVAILABLE := "PROVIDER_UNAVAILABLE"
const ERR_WORKSPACE_DENIED := "WORKSPACE_DENIED"
const ERR_SESSION_BUSY := "SESSION_BUSY"
const ERR_INTERNAL := "INTERNAL"
const ERROR_CODES := ["AUTH_FAILED", "BAD_REQUEST", "NOT_FOUND", "INSUFFICIENT_RESOURCES", "INSUFFICIENT_MANA", "AGE_REQUIRED", "RANK_REQUIRED", "LIMIT_REACHED", "INVALID_STATE", "CONFLICT", "PROVIDER_UNAVAILABLE", "WORKSPACE_DENIED", "SESSION_BUSY", "INTERNAL"]

const TERMINAL_TASK_STATES := ["accepted", "rejected", "cancelled"]

# Task.state
class TaskState:
	const IN_TRANSIT := "in_transit"
	const QUEUED := "queued"
	const PREPARING := "preparing"
	const RUNNING := "running"
	const AWAITING_APPROVAL := "awaiting_approval"
	const AWAITING_REVIEW := "awaiting_review"
	const ACCEPTING := "accepting"
	const ACCEPTED := "accepted"
	const REJECTED := "rejected"
	const PAUSED := "paused"
	const FAILED := "failed"
	const CANCELLED := "cancelled"
	const ALL := ["in_transit", "queued", "preparing", "running", "awaiting_approval", "awaiting_review", "accepting", "accepted", "rejected", "paused", "failed", "cancelled"]

# Task.state_reason when paused
class PauseReason:
	const BUDGET := "budget"
	const RESTART := "restart"
	const STALLED := "stalled"
	const MANA_DEPLETED := "mana_depleted"
	const PROVIDER_LIMIT := "provider_limit"
	const ALL := ["budget", "restart", "stalled", "mana_depleted", "provider_limit"]

# Task.size
class TaskSize:
	const S := "S"
	const M := "M"
	const L := "L"
	const XL := "XL"
	const ALL := ["S", "M", "L", "XL"]

# Task.courier.mode
class CourierMode:
	const HUMAN := "human"
	const WISP := "wisp"
	const EXPRESS := "express"
	const ALL := ["human", "wisp", "express"]

# task_progress.phase
class ProgressPhase:
	const PREPARING := "preparing"
	const WORKING := "working"
	const TOOL := "tool"
	const DELEGATING := "delegating"
	const FINISHING := "finishing"
	const RITE := "rite"
	const ALL := ["preparing", "working", "tool", "delegating", "finishing", "rite"]

# task_activity entry.kind
class ActivityKind:
	const MESSAGE := "message"
	const TOOL_START := "tool_start"
	const TOOL_END := "tool_end"
	const ERROR := "error"
	const SYSTEM := "system"
	const ALL := ["message", "tool_start", "tool_end", "error", "system"]

# Agent.lifecycle
class AgentLifecycle:
	const TRAINING := "training"
	const SETTLING := "settling"
	const ACTIVE := "active"
	const RETIRED := "retired"
	const ALL := ["training", "settling", "active", "retired"]

# Agent.activity
class AgentActivity:
	const IDLE := "idle"
	const WORKING := "working"
	const AWAITING_APPROVAL := "awaiting_approval"
	const BLOCKED := "blocked"
	const ALL := ["idle", "working", "awaiting_approval", "blocked"]

# Agent.blocked_reason
class BlockedReason:
	const MISSING_TOOLS := "missing_tools"
	const NO_MANA := "no_mana"
	const PROVIDER_OFFLINE := "provider_offline"
	const WORKSPACE_ERROR := "workspace_error"
	const ALL := ["missing_tools", "no_mana", "provider_offline", "workspace_error"]

# Agent.role
class Role:
	const ARTIFICER := "artificer"
	const SCHOLAR := "scholar"
	const SCRIBE := "scribe"
	const WARDEN := "warden"
	const HERALD := "herald"
	const ALL := ["artificer", "scholar", "scribe", "warden", "herald"]

# Agent.provider
class Provider:
	const CLAUDE := "claude"
	const CODEX := "codex"
	const PI := "pi"
	const ALL := ["claude", "codex", "pi"]

# Agent.approval_mode
class ApprovalMode:
	const ASK_EVERY_TIME := "ask_every_time"
	const TRUSTED_EDITS := "trusted_edits"
	const PLAN_FIRST := "plan_first"
	const FREE_HAND := "free_hand"
	const ALL := ["ask_every_time", "trusted_edits", "plan_first", "free_hand"]

# Agent.workspace.mode
class WorkspaceMode:
	const GIT_WORKTREE := "git_worktree"
	const PLAIN_FOLDER := "plain_folder"
	const ALL := ["git_worktree", "plain_folder"]

# Agent.billing
class Billing:
	const API_KEY := "api_key"
	const SUBSCRIPTION := "subscription"
	const ALL := ["api_key", "subscription"]

# check_providers billing_hint
class BillingHint:
	const API_KEY := "api_key"
	const SUBSCRIPTION := "subscription"
	const UNKNOWN := "unknown"
	const ALL := ["api_key", "subscription", "unknown"]

# ToolAddon.type
class ToolType:
	const LECTERN := "lectern"
	const QUILLWORKS := "quillworks"
	const FORGE := "forge"
	const ROOKERY := "rookery"
	const ARCHIVE := "archive"
	const WAYGATE := "waygate"
	const ALL := ["lectern", "quillworks", "forge", "rookery", "archive", "waygate"]

# ToolAddon.status
class ToolStatus:
	const BUILDING := "building"
	const ACTIVE := "active"
	const ERROR := "error"
	const REMOVED := "removed"
	const ALL := ["building", "active", "error", "removed"]

# Waygate config transport
class WaygateTransport:
	const STDIO := "stdio"
	const HTTP := "http"
	const ALL := ["stdio", "http"]

# Approval.category
class ApprovalCategory:
	const READ := "read"
	const WRITE := "write"
	const COMMAND := "command"
	const NETWORK := "network"
	const OUTSIDE_WORKSPACE := "outside_workspace"
	const MCP := "mcp"
	const ALL := ["read", "write", "command", "network", "outside_workspace", "mcp"]

# Approval.status
class ApprovalStatus:
	const PENDING := "pending"
	const ORPHANED := "orphaned"
	const ALL := ["pending", "orphaned"]

# Approval.scopes / respond_approval scope
class ApprovalScope:
	const ONCE := "once"
	const TASK := "task"
	const AGENT := "agent"
	const ALL := ["once", "task", "agent"]

# respond_approval decision
class ApprovalDecision:
	const ALLOW := "allow"
	const DENY := "deny"
	const ALL := ["allow", "deny"]

# approval_resolved.by
class ApprovalResolvedBy:
	const PLAYER := "player"
	const RULE := "rule"
	const PRE_APPROVAL := "pre_approval"
	const RESTART := "restart"
	const CANCELLED := "cancelled"
	const ALL := ["player", "rule", "pre_approval", "restart", "cancelled"]

# Approval.risk
class Risk:
	const LOW := "low"
	const MEDIUM := "medium"
	const HIGH := "high"
	const ALL := ["low", "medium", "high"]

# Incident.kind
class IncidentKind:
	const SMOKE := "smoke"
	const ALARM_BELL := "alarm_bell"
	const HAND_BELL := "hand_bell"
	const DIM_LANTERNS := "dim_lanterns"
	const FONT_DARK := "font_dark"
	const RIFT := "rift"
	const MERGE_BLOCKED := "merge_blocked"
	const ALL := ["smoke", "alarm_bell", "hand_bell", "dim_lanterns", "font_dark", "rift", "merge_blocked"]

# Incident.severity
class IncidentSeverity:
	const INFO := "info"
	const WARN := "warn"
	const URGENT := "urgent"
	const ALL := ["info", "warn", "urgent"]

# Mana.level
class ManaLevel:
	const NORMAL := "normal"
	const DIM := "dim"
	const WARNING := "warning"
	const DEPLETED := "depleted"
	const ALL := ["normal", "dim", "warning", "depleted"]

# Mana.period
class ManaPeriod:
	const DAY := "day"
	const WEEK := "week"
	const MONTH := "month"
	const ALL := ["day", "week", "month"]

# accept_result integrate
class Integrate:
	const MERGE := "merge"
	const KEEP_BRANCH := "keep_branch"
	const EXPORT := "export"
	const ALL := ["merge", "keep_branch", "export"]

# accept_result merge.blocked_reason
class MergeBlockedReason:
	const CHECKOUT_DIRTY := "checkout_dirty"
	const WRONG_BRANCH := "wrong_branch"
	const CONFLICT := "conflict"
	const MERGE_FAILED := "merge_failed"
	const EXPORT_CONFLICT := "export_conflict"
	const NOT_A_REPO := "not_a_repo"
	const WORKSPACE_MISSING := "workspace_missing"
	const ALL := ["checkout_dirty", "wrong_branch", "conflict", "merge_failed", "export_conflict", "not_a_repo", "workspace_missing"]

# get_task_detail diff.files[].status
class DiffFileStatus:
	const ADDED := "added"
	const MODIFIED := "modified"
	const DELETED := "deleted"
	const RENAMED := "renamed"
	const COPIED := "copied"
	const TYPE_CHANGED := "type_changed"
	const UNKNOWN := "unknown"
	const ALL := ["added", "modified", "deleted", "renamed", "copied", "type_changed", "unknown"]

# hello_result catchup
class Catchup:
	const REPLAY := "replay"
	const SNAPSHOT := "snapshot"
	const ALL := ["replay", "snapshot"]

# hello client.platform
class ClientPlatform:
	const DESKTOP := "desktop"
	const WEB := "web"
	const ALL := ["desktop", "web"]

# retire_agent when
class RetireWhen:
	const NOW := "now"
	const AFTER_CURRENT := "after_current"
	const ALL := ["now", "after_current"]

# resource keys
class ResourceName:
	const FOOD := "food"
	const WOOD := "wood"
	const STONE := "stone"
	const GOLD := "gold"
	const ALL := ["food", "wood", "stone", "gold"]

# set_setting key
class SettingKey:
	const WORK_WHILE_AWAY := "work_while_away"
	const EXPRESS_DISPATCH := "express_dispatch"
	const LANTERN_HOURS := "lantern_hours"
	const ALL := ["work_while_away", "express_dispatch", "lantern_hours"]
